---
title: "Untitled"
author: "XXX"
date: "MM/DD/2020"
output:
  html_document:
    theme: yeti
    highlight: pygments
    code_folding: hide
    
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE,fig.width=5,fig.height=5,comment="#R>")
```

# Packages and Data
```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r data}
wae <- read.csv("https://raw.githubusercontent.com/droglenc/FSAdata/master/data-raw/WalleyeErie2.csv") %>%
  filter(year==2003) %>%
  mutate(loc=plyr::mapvalues(loc,from=c(1,2,3),
                             to=c("Toledo-Huron","Huron-Fairport","Fairport-Conneaut")),
         loc=factor(loc))
str(wae)
```


## SECTION TITLE

Hello

```{r}
tl1 <- ggplot(data=wae,mapping=aes(x=tl)) +
  geom_histogram(color="gray30",fill="gray70",
             binwidth=10,boundary=0,closed="left") +
  scale_x_continuous(name="Total Length (mm)",breaks=seq(0,700,50),
    expand=expansion(mult=c(0,0))) +
  scale_y_continuous(name="Frequency of Walleye",
    expand=expansion(mult=c(0,0.05))) +
  theme_bw() +  
  theme(panel.grid.major.x=element_blank(),panel.grid.minor.x=element_blank(),
        panel.grid.minor.y=element_blank())
tl1
```
