---
######!!!!! DO NOT SAVE THIS AS TEMPLATE.Rmd ... GIVE IT A NEW NAME !!!!!######
title: "Lake Erie Walleye Lengths, 2003-2014"
author: "Derek Ogle"   ## Don't change next twelve lines
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: pygments
    code_folding: hide
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=TRUE,fig.width=6,fig.height=10,comment="#R>")
```

<!---- You can edit anything below here ---->

# Packages and Data
```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)

wae <- read.csv("https://raw.githubusercontent.com/droglenc/FSAdata/master/data-raw/WalleyeErie2.csv") %>%
  mutate(loc=plyr::mapvalues(loc,from=c(1,2,3),
              to=c("Toledo-Huron","Huron-Fairport","Fairport-Conneaut")),
         loc=factor(loc)) %>%
  select(-setID,-grid)
head(wae)
```

# The Visualization

```{r message=FALSE, warning=FALSE}
p <- ggplot() +
  geom_smooth(data=wae,mapping=aes(x=year,y=tl,color=sex)) +
  geom_jitter(data=wae,mapping=aes(x=year,y=tl,color=sex),alpha=0.025,
              position=position_dodge(width=0.1)) +
  facet_grid(rows=vars(loc)) +
  scale_x_continuous(name="Capture Year",breaks=seq(2003,2014,1)) +
  scale_y_continuous(name="Total Length (mm)",breaks=seq(200,800,100)) +
  scale_color_manual(name="Sex",values=c("blue","red")) +
  theme_bw() +
  theme(panel.grid.minor.x=element_blank(),
        legend.position=c(0.5,0.71),legend.title=element_blank(),
        legend.background=element_rect(fill="white",color=NA),
        legend.direction="horizontal")
p
```

<!---- Press Knit button in window toolbar to create HTML file ---->
